use college;
show tables;
create table Demo(SNo int, SName varchar(50), Phone varchar(20), Gender varchar(2));
select *from demo;
insert into demo values(4, 'Shebu', 9892503789, 'M');
select SName as Name from demo;
select *from demo as dmo;
select count (SName) from demo;
select avg(SNo) from demo;
select sum(SNo) from demo;
select min(SNo) from demo;
select max(SNo) from demo;
insert into demo values('','','','');
alter table demo add primary key (SNo);
alter table demo add unique key (SName);
desc demo;
create table practice(Id int PRIMARY KEY, FSName varchar(20), LSName varchar(20));
alter table practice modify Id int AUTO_INCREMENT;
insert into practice(FSName, LSName)values("Hardeep", "Singh");
select *from practice;
select count(Test1) Subcode from iamarks group by Subcode;
select count(Test1) ,FinalIA from iamarks group by FinalIA order by FinalIA desc;
select count(SSID) ,Subcode from iamarks group by Subcode having count(SSID)<=5417002021;
select *from subject;
select count(SSID) ,Subcode from iamarks group by Subcode having count(SSID)>=917002021;